# SimpleJetpacks Config
#

# Whether or not to use the <0.5 movement code
# Should apply on /simplejetpacks reload
old-motion: false

# Whether to enable the fueling GUI
fuel-gui: false

# Fuel items are defined below, with <ID>:<Fuel Amount>
items:
  COAL: 100
  CHARCOAL: 100
  REDSTONE: 50
  REDSTONE_BLOCK: 500

# Jetpacks are defined below
# After changing this a server restart is required to apply changes.
#
# fuel-capacity - the maximum amount of fuel this jetpack type can hold
# burn-rate - the amount of fuel this type burns per tick
# particles - list of particles to spawn when flying
# sound - sound to play when flying
# fly-speed - speed of jetpack
#
# recipe - this one is a little harder, recipe starts defining the recipe
#   r1 - the first row of the crafting table, as a three character string
#          spaces are nothing, letters get assigned to items later
#   r2 - r1 but second row
#   r3 - r3 but bottom row
#   items: - starts assigning items to the letters
#     A (or whatever letter you used in the recipe) - the item that this letter represents
#       You need one of these for each letter you used in r1, r2, and r3


jetpacks:
  LEATHER_CHESTPLATE:
    fuel-capacity: 500
    burn-rate: 2
    fly-speed: 0.8
    particles:
      - FLAME
      - FLAME
      - CAMPFIRE_COSY_SMOKE
    sound: BLOCK_FIRE_AMBIENT
    recipe:
      r1: " R "
      r2: "PCP"
      r3: " I "
      items:
        C: "LEATHER_CHESTPLATE"
        P: "PISTON"
        R: "REDSTONE_BLOCK"
        I: "IRON_INGOT"


  IRON_CHESTPLATE:
    fuel-capacity: 1000
    burn-rate: 1
    fly-speed: 1.2
    particles:
      - SOUL_FIRE_FLAME
      - SOUL_FIRE_FLAME
      - CAMPFIRE_COSY_SMOKE
    sound: ENTITY_CAT_PURR
    recipe:
      r1: "BRB"
      r2: "PCP"
      r3: "BAB"
      items:
        C: "IRON_CHESTPLATE"
        P: "PISTON"
        R: "REDSTONE_BLOCK"
        A: "ANVIL"
        B: "IRON_BLOCK"