# SimpleJetpacks Config
#

# Whether or not to use the <0.5 movement code
# Should apply on /simplejetpacks reload
old-motion: false


# Fuel items are defined below, with <ID>:<Fuel Amount>
items:
  COAL: 100
  CHARCOAL: 100
  REDSTONE: 50
  REDSTONE_BLOCK: 500

# Jetpacks are defined below, with <ID>:<Fuel Capacity>
# After changing this a server restart is required to apply changes.
jetpacks:
  LEATHER_CHESTPLATE: 500
  IRON_CHESTPLATE: 1000