name: SimpleJetpacks
version: 0.5.1
author: trainb0y1
main: io.github.trainb0y1.simplejetpacks.SimpleJetpacks
api-version: 1.16
commands:
  simplejetpacks:
    usage: /<command> [give | reload | version] <args>

  kotlin:
    usage:  /<command>

permissions:
  simplejetpacks.give:
    description: Allows players to give themselves jetpacks
  simplejetpacks.reload:
    description: Allows config file reload
