name: SimpleJetpacks
version: 0.6
author: trainb0y1
main: io.github.trainb0y1.simplejetpacks.SimpleJetpacks
api-version: 1.16
commands:
  simplejetpacks:
    usage: /<command> [give | reload] <args>

permissions:
  simplejetpacks.give:
    description: Allows giving players jetpacks
  simplejetpacks.reload:
    description: Allows config file reload
