name: SimpleJetpacks
version: 0.3
author: trainb0y1
main: io.github.trainb0y1.simplejetpacks.SimpleJetpacks
api-version: 1.16
commands:
  simplejetpacks:
    aliases: jetpacks
    usage: /<command> [give|reload]


permissions:
  simplejetpacks.give:
    description: Allows players to give themselves jetpacks
  simplejetpacks.reload:
    description: Allows config file reload
