name: SimpleJetpacks
version: 0.2
author: trainb0y1
main: io.github.trainb0y1.simplejetpacks.SimpleJetpacks
api-version: 1.16
commands:
  jetpack:
    description: gives caller a jetpack
    usage: /<command>